[package]
name = "your-username/project-name"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
Promise = "evaera/promise@^4.0.0"
GoodSignal = "stravant/goodsignal@^0.3.1"
Trove = "sleitnick/trove@^1.8.0"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@^1.0.3"
