[package]
name = "your-username/project-name"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
Promise = "evaera/promise"
GoodSignal = "stravant/goodsignal"
Trove = "sleitnick/trove"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore"
